/**
 ********************************************************************
 *
 * @copyright (c) 2023 DJI. All rights reserved.
 *
 * All information contained herein is, and remains, the property of DJI.
 * The intellectual and technical concepts contained herein are proprietary
 * to DJI and may be covered by U.S. and foreign patents, patents in process,
 * and protected by trade secret or copyright law.  Dissemination of this
 * information, including but not limited to data and other proprietary
 * material(s) incorporated within the information, in any form, is strictly
 * prohibited without the express written consent of DJI.
 *
 * If you receive this source code without DJI’s authorization, you may not
 * further disseminate the information, and you must immediately remove the
 * source code and notify DJI of its removal. DJI reserves the right to pursue
 * legal actions against you for any loss(es) or damage(s) caused by your
 * failure to do so.
 *
 *********************************************************************
 */

#ifndef __ESDK_INIT_OPTIONS_H_
#define __ESDK_INIT_OPTIONS_H_

#include <cstdint>
#include <string>
#include <list>

#include "logger.h"

namespace edge_sdk {

/* Exported types ------------------------------------------------------------*/
class KeyStore;

struct Version {
    uint8_t major_version;
    uint8_t minor_version;
    uint8_t modify_version;
    uint8_t debug_version;
};

/*
 * brief AppInfo
 * App certification information generated by DJI developer website account, can only successfully initialize EdgeSDK by filling in the accurate registration information
 */
struct AppInfo {
    std::string app_name;
    std::string app_id;
    std::string app_key;
    std::string app_license;
    std::string developer_account;
};

using FirmwareVersion = Version;
using ProductName = std::string;
using VendorName = std::string;
using SerialNumber = std::string;
using AppName = std::string;
using LoggerConsoleList = std::list<LoggerConsole>;

/*
 * brief: Initialize EdgeSDK configuration information
 */
struct Options {
    /*! Product name of the device */
    ProductName product_name;
    /*! Name of the device vendor */
    VendorName vendor_name;
    /*! Serial number of the device product, maintain uniqueness for each device */
    SerialNumber serial_number;
    /*! Firmware version number */
    FirmwareVersion firmware_version;
    /*! App authentication information generated from developer website */
    AppInfo app_info;
    /*! List of consoles for logging, supports adding multiple consoles */
    LoggerConsoleList logger_console_lists;
    /*! Implementation instance of the asymmetric key retrieval interface */
    std::shared_ptr<KeyStore> key_store;
};

}  // namespace edge_sdk

#endif
